export default {
  USER_LOGIN: '@auth/USER_LOGIN',
  USER_LOGIN_SUCCESS: '@auth/USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILURE: '@auth/USER_LOGIN_FAILURE',

  UPDATE_TOKENS_ON_STATE: '@auth/UPDATE_TOKENS_ON_STATE',
}
